version: "3"

networks:
  dns-network:
    driver: bridge
services:
  api:
    container_name: node-api
    image: node:current
    env_file:
      - .env.dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    command: /bin/bash -c 'yarn start:dev'
    networks:
      - dns-network
    depends_on:
      - dns-test-service

  dns-test-service:
    container_name: go-api
    build:
      context: ./dns_test_service
    ports: 
      - 8080:8080 
    restart: on-failure
    networks:
      - dns-network
